---
- name: This is a kind of learning playbook concept.
  hosts: all
  become: yes
  tasks:
  - name: To Install httpd package
    yum:
     name: httpd
     state: installed

  - name: Start service httpd, if not started
    service:
     name: httpd
     state: started
